### ISSUE TITLE
unraid davfs2 install err

### ISSUE THREAD

**Issue by suosuosi** [greycubesgav/unraid-templates#2]
`Adding davfs2 group....
plugin: run failed: '/bin/bash' returned 9
Executing hook script: post_plugin_checks`

solved

**Comment by shanyan-wcx** [comment]
> `Adding davfs2 group.... plugin: run failed: '/bin/bash' returned 9 Executing hook script: post_plugin_checks`
> 
> solved 解决

Hey, how did you solve it?
