### ISSUE TITLE
can't mount

### ISSUE THREAD

**Issue by emcd39** [greycubesgav/unraid-templates#3]
/sbin/mount.davfs: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
unraid 7.0.0-beta.2

**Comment by greycubesgav** [comment]
Thanks for the update, I've not tried running Unraid 7 yet.

Would you mind running the following commands under your Unraid terminal?

```
ldd /sbin/mount.davfs
```

```
ldd /usr/bin/openssl
```

```
ls -l /lib64/libssl*
```

I'm wondering if the version of libssl has just been bumped up in Unraid 7.

Thanks
Gavin

**Comment by s1oz** [comment]
> Thanks for the update, I've not tried running Unraid 7 yet.
> 
> Would you mind running the following commands under your Unraid terminal?
> 
> ```
> ldd /sbin/mount.davfs
> ```
> 
> ```
> ldd /usr/bin/openssl
> ```
> 
> ```
> ls -l /lib64/libssl*
> ```
> 
> I'm wondering if the version of libssl has just been bumped up in Unraid 7.
> 
> Thanks
> Gavin
> 
```
root@Tower:~# ldd /sbin/mount.davfs
        linux-vdso.so.1 (0x00007ffe3eda0000)
        libneon.so.27 => /usr/lib64/libneon.so.27 (0x000015521a1c0000)
        libz.so.1 => /lib64/libz.so.1 (0x000015521a1a6000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x000015521a153000)
        libproxy.so.1 => /usr/lib64/libproxy.so.1 (0x000015521a12e000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x000015521a104000)
        libc.so.6 => /lib64/libc.so.6 (0x0000155219f04000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x0000155219e30000)        libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x0000155219e03000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x0000155219dfd000)
        libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x0000155219def000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x0000155219de8000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x0000155219dd6000)        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000155219dcf000)
        libdl.so.2 => /lib64/libdl.so.2 (0x0000155219dca000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000155219b6c000)
        libm.so.6 => /lib64/libm.so.6 (0x0000155219a83000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x0000155219a5e000)
        /lib64/ld-linux-x86-64.so.2 (0x000015521a1fe000)
root@Tower:~# ldd /usr/bin/openssl
        linux-vdso.so.1 (0x00007ffea4d69000)
        libssl.so.3 => /lib64/libssl.so.3 (0x0000154092cd5000)
        libcrypto.so.3 => /lib64/libcrypto.so.3 (0x0000154092792000)        libz.so.1 => /lib64/libz.so.1 (0x0000154092778000)
        libc.so.6 => /lib64/libc.so.6 (0x0000154092578000)
        /lib64/ld-linux-x86-64.so.2 (0x0000154092de9000)
root@Tower:~# ls -l /lib64/libssl*
-rwxr-xr-x 1 root root 1065064 Jun  6 01:29 /lib64/libssl.so.3*
root@Tower:~#
```

**Comment by emcd39** [comment]
Mine is the same as the one above, it looks like the libssl version got updated in the 7.0 upgrade

**Comment by greycubesgav** [comment]
I've just published a new version that includes provisional support for Unraid 7.

You can install it manually using the Unraid webgui from "Plugins" -> "Install Plugin" -> "Enter URL of remote plugin file or local plugin file"
Url: https://raw.githubusercontent.com/greycubesgav/unraid-templates/main/davfs2/davfs2.plg

Let me know if this works for you

**Comment by s1oz** [comment]
Thank you, the plugin is working fine now

> I've just published a new version that includes provisional support for Unraid 7.
> 
> You can install it manually using the Unraid webgui from "Plugins" -> "Install Plugin" -> "Enter URL of remote plugin file or local plugin file" Url: https://raw.githubusercontent.com/greycubesgav/unraid-templates/main/davfs2/davfs2.plg
> 
> Let me know if this works for you

Thank you, the plugin is working fine now
