### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by shanyan-wcx** [greycubesgav/unraid-templates#4]
plugin: installing: davfs2.plg
Executing hook script: pre_plugin_checks
plugin: downloading: davfs2.plg ... done

Executing hook script: pre_plugin_checks
Removing all old packages and scripts...
Adding davfs2 user and group 230:230 ....
davfs2:x:230:
plugin: downloading: install_pkgs.sh ... done

Downloading package: neon-0.32.2-x86_64-1.txz
Failed to download pkg to /boot/config/plugins/davfs2/neon-0.32.2-x86_64-1.txz from: https://github.com/greycubesgav/unraid-templates/raw/main/davfs2/packages/neon-0.32.2-x86_64-1.txz
plugin: run failed: '/usr/bin/env bash' returned 10
Executing hook script: gui_search_post_hook.sh
Executing hook script: post_plugin_checks

**Comment by greycubesgav** [comment]
Hi, 
What version of Unraid are you running?
Remote url path shown in the error is correct, are you able to curl this file from an unraid command prompt directly?
Thanks
Gavin

**Comment by shanyan-wcx** [comment]
I tried several times and the installation was successful. It seems to be a network issue.
